language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.3
    - android-27
    - android-25

    - extra-android-m2repository
    - extra-google-m2repository


  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
   - ./gradlew build



